language: python
dist: xenial
sudo: true
python:
- '3.7'
- '3.8'
- '3.9'
install:
- python setup.py install
before_script:
  - pip install nox
script:
- nox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
  - stage: deploy
    python: '3.7'  # 3.7 is installed in system so build will be faster
    script: skip
    deploy:
      provider: pypi
      user: "__token__"
      password:
        secure: "G+RBbwxWghIghIXGRR2Rf1VDYIs1ajyDVesqgrL8jyGP0I6w1FG+rlKoUPXS3KnA/o09KbE5AKYVAID1NYYSrXA2uMt5uMpEqYh99PuUrn+0kDNWfOWjhuDXaKbNM6EuX2NbZfg/W8/uakV6j88v1DQK1WZuFCi3wC6fGfIP/NdKAV+zBBg00z6LlRZIsU0CGwInBitxZ0tZTaIoH4JQoqpiYA9Y3QfiBAWLuZ0hoN9mt4PK6suioJx+XUmVUlT68TKI1fA29v0NLaqf+YYFdT6PRU51Ds/TPaAV7bljPE7wCSkeDPQ3ozA75FxDUV0pLrAszcJpozbUFJdRvVx8CHWUN2zUfUfMljrTSEARqm+9FUnkzEtRGRcgvpZYsMAbGmLqbDHJD1JaaXYj4TDUOG+Sy/Vju2FpA3RTSLqtEitsMtSdXGGXFOmU1BwDpV7b/38qWzBwq7NQ723MZaFZxV55RQPQ9GT/JYaP/MNLe53RZ0hbisGJ7SEplnTvYgxt+plTuiapW8ydZNWyOQAZXhMtfWGvJF7JqCpEzP/Uo3eZoH21TageMs4HfL2ajK4W6S2OyxcEM9YNCyYExptJcm1+isIm0i0CZ1ZcKqauhUguzs2mXyqBCvgzitPyJKB7m7JR3/uG7CgXYWwHK3lY44X++ZB/CEOGvs2VeIvvazE="
      on:
        distributions: sdist bdist_wheel
        repo: tapas-scaffold-tool/tapas
    after_deploy:
    - git config --local user.name "Bender Rodriguez"
    - git config --local user.email "ksbenderbot@ya.ru"
    - git tag $(cat tapas/tapas.version)
