language: python
dist: xenial
sudo: true
python:
- '3.7'
- '3.8'
- '3.9'
install:
- python setup.py install
before_script:
  - pip install nox
script:
- nox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
  - stage: deploy
    python: '3.7'  # 3.7 is installed in system so build will be faster
    script: skip
    before_deploy:
      - git config --local user.name "Bender Rodriguez"
      - git config --local user.email "ksbenderbot@ya.ru"
      - git tag $(cat tapas/tapas.version) --force
    deploy:
    - provider: pypi
      user: "__token__"
      password:
        secure: "G+RBbwxWghIghIXGRR2Rf1VDYIs1ajyDVesqgrL8jyGP0I6w1FG+rlKoUPXS3KnA/o09KbE5AKYVAID1NYYSrXA2uMt5uMpEqYh99PuUrn+0kDNWfOWjhuDXaKbNM6EuX2NbZfg/W8/uakV6j88v1DQK1WZuFCi3wC6fGfIP/NdKAV+zBBg00z6LlRZIsU0CGwInBitxZ0tZTaIoH4JQoqpiYA9Y3QfiBAWLuZ0hoN9mt4PK6suioJx+XUmVUlT68TKI1fA29v0NLaqf+YYFdT6PRU51Ds/TPaAV7bljPE7wCSkeDPQ3ozA75FxDUV0pLrAszcJpozbUFJdRvVx8CHWUN2zUfUfMljrTSEARqm+9FUnkzEtRGRcgvpZYsMAbGmLqbDHJD1JaaXYj4TDUOG+Sy/Vju2FpA3RTSLqtEitsMtSdXGGXFOmU1BwDpV7b/38qWzBwq7NQ723MZaFZxV55RQPQ9GT/JYaP/MNLe53RZ0hbisGJ7SEplnTvYgxt+plTuiapW8ydZNWyOQAZXhMtfWGvJF7JqCpEzP/Uo3eZoH21TageMs4HfL2ajK4W6S2OyxcEM9YNCyYExptJcm1+isIm0i0CZ1ZcKqauhUguzs2mXyqBCvgzitPyJKB7m7JR3/uG7CgXYWwHK3lY44X++ZB/CEOGvs2VeIvvazE="
      on:
        distributions: sdist bdist_wheel
        repo: tapas-scaffold-tool/tapas
    - provider: releases
      api_key:
        secure: "L8lro/ttdT6mWxD0TwTH13PP4WZN3eiH+g8SaAZg4/zYXrrqX9xkVgAaFtryQXkiE8H+0xncRcvK8GhLO4fSv9ZsZVuR13jyi1xK2Lf6RaV4JILoyDFiKU5sW2DQ1C82PNsNC0akmCX6MEJ0/bqErC8iqqdkriUSZ5sneG7JsKSuxU6lIXMTedzCPIvU6RvzlA83y+yQ433MP+Riz3+qbrpJ2F0VeIgcHd+xbXYF3MVsFB53UZEiVzL58hvv1GA782PnzTXXWMZ2qLsA5ISdm9UyhrZelDO92owL3bZ6VfVAJnRbLF9VzjD3BzAFTy1AeSgMfaCu2dsdlddnMIR4QksRd5uaGVz7OthB2VGvulYnbzLW2mPSO2vAxb7t9/o135CybbrbNlL1maSzMMuTyTufC8pbNa1acIv/zHeeiKn50ANdQfJvOcGsIHLOiO1AU/ZWz8qDELty24s0M6Pnxebkg/HL79ZKayTabLvgLoAIkbySkYLrGkFN/Sz0N2xgn3Yvj9rfnXpG/CEvYE6dqUXc6tzGWgjieMHbiGBRUgu+yDm44irwqk+3Ta6AA7Kultpfvs0QhLUpc+DEXjvH/ogr7C5q62RlN2K3GdjNBu8vrwEYm7wDhOiIR4OL1pXlKfu/ssNHB52kf9ijjzgxFBwznpgYOu1iXYxhXpFRmz4="
      on:
        repo: tapas-scaffold-tool/tapas
      skip_cleanup: true
